version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "3307:3306"
    environment:
     MYSQL_ROOT_PASSWORD: example_pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
    - "8002:80"
    environment:
      PMA_PORT: db
      PMA_USER: example
      PMA_PASSWORD: example_passs

  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    restart: always
    volumes:
      - "./dev/nginx_conf:/etc/nginx/conf.d"
      - "./assets:/home/EXAMPLE_AUCTION/assets"
    depends_on:
      - auction

  auction:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./:/usr/projects/current"
    environment:
      - LEVEL=TEST
    command: bash -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 EXAMPLE_AUCTION.wsgi --reload && python manage.py starttornadoapp"
    depends_on:
      - db


