# Generated by Django 2.2.7 on 2019-12-09 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        ('EXAMPLE_AUCTION', '0001_initial'),
        ('EXAMPLE_AUCTION', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionparticipationorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profile.Company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='auctionparticipationorder',
            name='participation_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='EXAMPLE_AUCTION.ParticipationStatus', verbose_name='Статус участия'),
        ),
        migrations.AddField(
            model_name='auctiondeal',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXAMPLE_AUCTION.AuctionBet'),
        ),
        migrations.AddField(
            model_name='auctiondeal',
            name='seller_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXAMPLE_AUCTION.AuctionSellerOffer'),
        ),
        migrations.AddField(
            model_name='auctionbet',
            name='EXAMPLE_AUCTION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EXAMPLE_AUCTION.Auction'),
        ),
        migrations.AddField(
            model_name='auctionbet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='EXAMPLE_AUCTION',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EXAMPLE_AUCTION.BidLevel', verbose_name='Уровень заявки'),
        ),
        migrations.AddField(
            model_name='EXAMPLE_AUCTION',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='EXAMPLE_AUCTION',
            name='shipment_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EXAMPLE_AUCTION.ShipmentConditions', verbose_name='Условия при торгах'),
        ),
        migrations.AddField(
            model_name='EXAMPLE_AUCTION',
            name='trading_operation',
            field=models.ForeignKey(db_column='trading_operation', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='EXAMPLE_AUCTION.TradingOperation', verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='EXAMPLE_AUCTION',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EXAMPLE_AUCTION.TradingType', verbose_name='Операция'),
        ),
        migrations.AlterUniqueTogether(
            name='auctionparticipationorder',
            unique_together={('EXAMPLE_AUCTION', 'company')},
        ),
    ]
