# Generated by Django 2.2.7 on 2019-12-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXAMPLE_AUCTION', '0001_initial'),
        ('EXAMPLE_AUCTION', '0002_auto_20191209_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='EXAMPLE_AUCTION',
            name='docs',
            field=models.ManyToManyField(to='EXAMPLE_AUCTION.Document'),
        ),
    ]
