# Generated by Django 2.2.7 on 2019-12-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EXAMPLE_AUCTION', '0003_auction_docs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctiondeal',
            old_name='pay_cheque',
            new_name='file_path',
        ),
    ]
