# Generated by Django 2.2.7 on 2019-12-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('date', models.DateField(verbose_name='Дата статьи')),
                ('write_time', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
        ),
    ]
